# Generated by Django 5.2.5 on 2025-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("UPI", "UPI (Any UPI App)"),
                    ("PHONEPE", "PhonePe"),
                    ("GPAY", "Google Pay"),
                    ("PAYTM", "Paytm"),
                    ("CARD", "Credit/Debit Card"),
                    ("CASH", "Cash"),
                ],
                default="UPI",
                max_length=10,
            ),
        ),
    ]
